**Exercise 1**

Cosider the system

\begin{equation}
    \begin{cases}
        2x+y=z+8\\
        -3x=y-2z-11\\ \label{eq1} \tag{1}
        -2x+y+2z=-3,
    \end{cases}
\end{equation}
write it in the form of $Ax=b$.

(a) Use **LU factorization** to solve the system \eqref{eq1} (*use your own forward and backward substituion function code, to be submitted*)

$\begin{bmatrix}2 & 1 & -1\\ 3 & 1 & -2\\ -2 & 1 & 2\end{bmatrix}\begin{bmatrix}x_1\\x_2\\x_3\end{bmatrix}=\begin{bmatrix}8\\11\\-3\end{bmatrix}$

In [12]:
using LinearAlgebra

In [7]:
function forward_sub(A,b)
    n = size(A)[1]
    x = zeros(n)
    
    for i in 1:n
        for j in 1:(i-1)
            b[i] = b[i]-(A[j,j]*x[j])        
        end
        x[i] = b[i]/A[i,i]
    end
    return x
end


function backward_sub(A,b)
    n = size(A)[1]
    x = zeros(n)
    
    for i in n:-1:1
        for j in (i+1):n
            b[i] = b[i]-(A[j,j]*x[j])        
        end
        x[i] = b[i]/A[i,i]
    end
    return x

end

backward_sub (generic function with 1 method)

In [13]:
A = [2 1 -1; 3 1 -2; -2 1 2]
b = [8; 11; -3]
L, U = LinearAlgebra.lu(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
  1.0       0.0  0.0
 -0.666667  1.0  0.0
  0.666667  0.2  1.0
U factor:
3×3 Matrix{Float64}:
 3.0  1.0      -2.0
 0.0  1.66667   0.666667
 0.0  0.0       0.2

In [18]:
L

3×3 Matrix{Float64}:
  1.0       0.0  0.0
 -0.666667  1.0  0.0
  0.666667  0.2  1.0

In [19]:
y = forward_sub(L, b)

3-element Vector{Float64}:
   8.0
   3.0
 -14.0

In [20]:
x = backward_sub(U, y)

3-element Vector{Float64}:
   1.6666666666666667
  10.200000000000001
 -70.00000000000001

(b) Can you solve the system of equations (1) above by Cholesky decomposition ? why ?

In [21]:
isposdef(A)

false

No because the matrix is not positive definite

(c) Can the system (1) above be stable to a small change in b ? why?

In [22]:
cond(A,1)

77.00000000000003

No it is not stable since the condition number is very different from 1

**Exercise 2**

Let $$A = \begin{pmatrix}2&-1\\0&1\\2&2\end{pmatrix}, \quad b=\begin{pmatrix}1\\-5\\6\end{pmatrix}\quad \text{such that}\quad Ax=b,\quad x\in\mathbb{R}^2  \label{eq2}\tag{2}$$

(a) Explain the different steps to solve problem \eqref{eq2} above.

In [23]:
A = [2 -1; 0 1; 2 2]
b = [1; -5; 6]

3-element Vector{Int64}:
  1
 -5
  6

We can use QR decomposition to solve the system above. We can also use Singular value decomposition to solve the system above. Finally we can use the idea of pseudoinverses although that is generally not computationally efficient.

(b) Use your forward and backward function code to solve the problem (2) above.

In [24]:
L, U = lu(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×2 Matrix{Float64}:
 1.0  0.0
 1.0  1.0
 0.0  0.333333
U factor:
2×2 Matrix{Float64}:
 2.0  -1.0
 0.0   3.0

In [19]:
L=[2 0 0;4 1 0;-6 -1 2]

3×3 Matrix{Int64}:
  2   0  0
  4   1  0
 -6  -1  2

In [22]:
U = [1 -1/2 0; 0 1 2; 0 0 1]

3×3 Matrix{Float64}:
 1.0  -0.5  0.0
 0.0   1.0  2.0
 0.0   0.0  1.0

In [23]:
b = [-2 14 12]'

3×1 adjoint(::Matrix{Int64}) with eltype Int64:
 -2
 14
 12

In [26]:
y=b\L

1×3 Matrix{Float64}:
 -0.0581395  0.00581395  0.0697674

In [27]:
x=y'\U

1×3 Matrix{Float64}:
 -7.02041  4.21224  9.82857

In [28]:
A = L*U

3×3 Matrix{Float64}:
  2.0  -1.0  0.0
  4.0  -1.0  2.0
 -6.0   2.0  0.0

In [29]:
det(L)*det(U)

4.0

In [30]:
det(A)

4.0

In [47]:
zz = [1 5;1.0001 5]

2×2 Matrix{Float64}:
 1.0     5.0
 1.0001  5.0

In [48]:
f = qr(zz)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor: 2×2 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}
R factor:
2×2 Matrix{Float64}:
 -1.41428  -7.07107
  0.0      -0.000353536

In [49]:
f.R

2×2 Matrix{Float64}:
 -1.41428  -7.07107
  0.0      -0.000353536

In [50]:
Q = f.Q*I

2×2 Matrix{Float64}:
 -0.707071  -0.707142
 -0.707142   0.707071

In [45]:
ll = inv(Q)*br

2×1 Matrix{Float64}:
 -8.485634934699966
 -7.070714267241433e-5

In [39]:
br = [6.0000 6.0005]'

2×1 adjoint(::Matrix{Float64}) with eltype Float64:
 6.0
 6.0005

In [75]:
f.R\ll

2×1 Matrix{Float64}:
 5.000000000010307
 0.19999999999793847

In [76]:
f.R\bb

2×1 Matrix{Float64}:
 4.999999999997747
 0.20000000000045073

In [51]:
br\zz

1×2 Matrix{Float64}:
 0.166668  0.833299

In [52]:
det(zz)

-0.0005000000000000831

In [53]:
zz

2×2 Matrix{Float64}:
 1.0     5.0
 1.0001  5.0

In [54]:
dd = [6 6]'

2×1 adjoint(::Matrix{Int64}) with eltype Int64:
 6
 6

In [55]:
dd\zz


1×2 Matrix{Float64}:
 0.166675  0.833333

In [56]:
A = [1 0 1;-1 1 1; -1 -1 1]

3×3 Matrix{Int64}:
  1   0  1
 -1   1  1
 -1  -1  1

In [57]:
F = lu(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
  1.0   0.0  0.0
 -1.0   1.0  0.0
 -1.0  -1.0  1.0
U factor:
3×3 Matrix{Float64}:
 1.0  0.0  1.0
 0.0  1.0  2.0
 0.0  0.0  4.0

In [58]:
b = [1 1 1]'

3×1 adjoint(::Matrix{Int64}) with eltype Int64:
 1
 1
 1

In [59]:
P = F.P

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [60]:
y = b\F.L

1×3 Matrix{Float64}:
 -0.333333  -0.0  0.333333

In [62]:
x = y'\F.U

1×3 Matrix{Float64}:
 -1.5  0.0  4.5

In [66]:
xx=b\A

1×3 Matrix{Float64}:
 -0.333333  -0.0  1.0

In [67]:
A*xx'

3×1 Matrix{Float64}:
 0.6666666666666666
 1.3333333333333335
 1.3333333333333335

In [68]:
A

3×3 Matrix{Int64}:
  1   0  1
 -1   1  1
 -1  -1  1

In [71]:
F = lu(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
  1.0   0.0  0.0
 -1.0   1.0  0.0
 -1.0  -1.0  1.0
U factor:
3×3 Matrix{Float64}:
 1.0  0.0  1.0
 0.0  1.0  2.0
 0.0  0.0  4.0

In [72]:
b

3×1 adjoint(::Matrix{Int64}) with eltype Int64:
 1
 1
 1

In [73]:
F.p

3-element Vector{Int64}:
 1
 2
 3

In [74]:
y

1×3 Matrix{Float64}:
 -0.333333  -0.0  0.333333

In [80]:
C = [1 2 -1;2 1 3;5 8 2]

3×3 Matrix{Int64}:
 1  2  -1
 2  1   3
 5  8   2

In [81]:
F2 = lu(C)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
 1.0   0.0       0.0
 0.4   1.0       0.0
 0.2  -0.181818  1.0
U factor:
3×3 Matrix{Float64}:
 5.0   8.0   2.0
 0.0  -2.2   2.2
 0.0   0.0  -1.0

In [82]:
F2.P

3×3 Matrix{Float64}:
 0.0  0.0  1.0
 0.0  1.0  0.0
 1.0  0.0  0.0

In [83]:
U2 = F2.U

3×3 Matrix{Float64}:
 5.0   8.0   2.0
 0.0  -2.2   2.2
 0.0   0.0  -1.0

In [84]:
L2 = F2.L

3×3 Matrix{Float64}:
 1.0   0.0       0.0
 0.4   1.0       0.0
 0.2  -0.181818  1.0

In [88]:
b1 = [2 1 1]'

3×1 adjoint(::Matrix{Int64}) with eltype Int64:
 2
 1
 1

In [92]:
b2 = F2.P'*b1

3×1 Matrix{Float64}:
 1.0
 1.0
 2.0

In [93]:
y2 = F2.L\b2

3×1 Matrix{Float64}:
 1.0
 0.6
 1.9090909090909092

In [94]:
x2 = F2.U\y2

3×1 Matrix{Float64}:
  4.454545454545455
 -2.1818181818181817
 -1.9090909090909092

In [96]:
x2 = F2.U\(F2.L\b2)

3×1 Matrix{Float64}:
  4.454545454545455
 -2.1818181818181817
 -1.9090909090909092

In [97]:
C*x2

3×1 Matrix{Float64}:
 2.000000000000001
 1.0000000000000009
 1.0000000000000018

In [1]:
using LinearAlgebra

In [2]:
A = [1 2; 1 3]

2×2 Matrix{Int64}:
 1  2
 1  3

In [3]:
A[:,1]

2-element Vector{Int64}:
 1
 1

In [12]:
function my_qr(A, b)
    c = A[1, 1]/LinearAlgebra.norm(A[:,1], 2)
    s = A[2, 1]/LinearAlgebra.norm(A[:,1], 2)
    
    Q = [c -s; s c]
    Qprime = Q'
    
    R = Qprime*A
    
    x = R\(Qprime*b)
    return x
end

my_qr (generic function with 1 method)

In [13]:
A = [1 2; 1 3]
b = [1; 2]

2-element Vector{Int64}:
 1
 2

In [14]:
my_qr(A, b)

2-element Vector{Float64}:
 -1.0
  1.0

In [26]:
x = [2; -1; 2]

3-element Vector{Int64}:
  2
 -1
  2

In [22]:
diagm()

LoadError: UndefVarError: `eyes` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [60]:
function householder_reflector(x)
    """This is a function that takes in an input x and zeros out all but the first entry"""
    x = reshape(x, length(x), 1) #First we make sure the input vector is a column vector
    n = length(x) #We generate the length of the column vector and call it n
    norm_x = LinearAlgebra.norm(x, 2) #We calculate the norm of the input vector
    y = zeros(n) #We initialize the y vector with zeros
    sign_x = sign(x[1]) #We get the sign of the first element of the column vector
    y[1] = sign_x*norm_x #We get the correct value of the first element of the y vector
    
    I = Matrix(1LinearAlgebra.I, n, n) #We initialize the identity matrix of order n
    
    
    u = x-y #We calculate the value of u
    γ = 2/((LinearAlgebra.norm(u,2))^2) #We generate the value of γ to use in the equation for the householder reflector 
    
    H = I - γ*(u*u') #We use the general formula for generating the householder reflector to get H
    return H #We return H
end

householder_reflector (generic function with 1 method)

In [63]:
x = [1 2 3 4]

1×4 Matrix{Int64}:
 1  2  3  4

In [66]:
householder_reflector(x)*x'

4×1 Matrix{Float64}:
  5.477225575051661
 -2.220446049250313e-16
 -4.440892098500626e-16
 -4.440892098500626e-16

In [55]:
householder_reflector(x)

4×4 Matrix{Float64}:
 0.182574   0.365148   0.547723   0.730297
 0.365148   0.836886  -0.244671  -0.326227
 0.547723  -0.244671   0.632994  -0.489341
 0.730297  -0.326227  -0.489341   0.347545

In [59]:
Matrix(LinearAlgebra.I*1, 3, 3)

3×3 Matrix{Int64}:
 1  0  0
 0  1  0
 0  0  1