In [10]:
using LinearAlgebra

In [11]:
function lsq_n(A, b)
    Aprime = A'
    B = Aprime*A
    bhat = Aprime*b
    R = cholesky(B).U
    y = R'\bhat
    x = R\y
    return x
end

lsq_n (generic function with 1 method)

In [12]:
A = [1 3 1; 1 3 7; 1 -1 -9; 1 -1 2]
b = [1; 1; 1; 1]

lsq_n(A, b)

3-element Vector{Float64}:
 1.0
 0.0
 0.0

In [13]:
C = cholesky(A'*A)

Cholesky{Float64, Matrix{Float64}}
U factor:
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 2.0  2.0  0.5
  ⋅   4.0  7.5
  ⋅    ⋅   8.86002

In [14]:
?cholesky

search: cholesky cholesky! Cholesky coalesce



```julia
cholesky(A, NoPivot(); check = true) -> Cholesky
```

Compute the Cholesky factorization of a dense symmetric positive definite matrix `A` and return a [`Cholesky`](@ref) factorization. The matrix `A` can either be a [`Symmetric`](@ref) or [`Hermitian`](@ref) [`AbstractMatrix`](@ref) or a *perfectly* symmetric or Hermitian `AbstractMatrix`.

The triangular Cholesky factor can be obtained from the factorization `F` via `F.L` and `F.U`, where `A ≈ F.U' * F.U ≈ F.L * F.L'`.

The following functions are available for `Cholesky` objects: [`size`](@ref), [`\`](@ref), [`inv`](@ref), [`det`](@ref), [`logdet`](@ref) and [`isposdef`](@ref).

If you have a matrix `A` that is slightly non-Hermitian due to roundoff errors in its construction, wrap it in `Hermitian(A)` before passing it to `cholesky` in order to treat it as perfectly Hermitian.

When `check = true`, an error is thrown if the decomposition fails. When `check = false`, responsibility for checking the decomposition's validity (via [`issuccess`](@ref)) lies with the user.

# Examples

```jldoctest
julia> A = [4. 12. -16.; 12. 37. -43.; -16. -43. 98.]
3×3 Matrix{Float64}:
   4.0   12.0  -16.0
  12.0   37.0  -43.0
 -16.0  -43.0   98.0

julia> C = cholesky(A)
Cholesky{Float64, Matrix{Float64}}
U factor:
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 2.0  6.0  -8.0
  ⋅   1.0   5.0
  ⋅    ⋅    3.0

julia> C.U
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 2.0  6.0  -8.0
  ⋅   1.0   5.0
  ⋅    ⋅    3.0

julia> C.L
3×3 LowerTriangular{Float64, Matrix{Float64}}:
  2.0   ⋅    ⋅
  6.0  1.0   ⋅
 -8.0  5.0  3.0

julia> C.L * C.U == A
true
```

---

```julia
cholesky(A, RowMaximum(); tol = 0.0, check = true) -> CholeskyPivoted
```

Compute the pivoted Cholesky factorization of a dense symmetric positive semi-definite matrix `A` and return a [`CholeskyPivoted`](@ref) factorization. The matrix `A` can either be a [`Symmetric`](@ref) or [`Hermitian`](@ref) [`AbstractMatrix`](@ref) or a *perfectly* symmetric or Hermitian `AbstractMatrix`.

The triangular Cholesky factor can be obtained from the factorization `F` via `F.L` and `F.U`, and the permutation via `F.p`, where `A[F.p, F.p] ≈ Ur' * Ur ≈ Lr * Lr'` with `Ur = F.U[1:F.rank, :]` and `Lr = F.L[:, 1:F.rank]`, or alternatively `A ≈ Up' * Up ≈ Lp * Lp'` with `Up = F.U[1:F.rank, invperm(F.p)]` and `Lp = F.L[invperm(F.p), 1:F.rank]`.

The following functions are available for `CholeskyPivoted` objects: [`size`](@ref), [`\`](@ref), [`inv`](@ref), [`det`](@ref), and [`rank`](@ref).

The argument `tol` determines the tolerance for determining the rank. For negative values, the tolerance is equal to `eps()*size(A,1)*maximum(diag(A))`.

If you have a matrix `A` that is slightly non-Hermitian due to roundoff errors in its construction, wrap it in `Hermitian(A)` before passing it to `cholesky` in order to treat it as perfectly Hermitian.

When `check = true`, an error is thrown if the decomposition fails. When `check = false`, responsibility for checking the decomposition's validity (via [`issuccess`](@ref)) lies with the user.

# Examples

```jldoctest
julia> X = [1.0, 2.0, 3.0, 4.0];

julia> A = X * X';

julia> C = cholesky(A, RowMaximum(), check = false)
CholeskyPivoted{Float64, Matrix{Float64}, Vector{Int64}}
U factor with rank 1:
4×4 UpperTriangular{Float64, Matrix{Float64}}:
 4.0  2.0  3.0  1.0
  ⋅   0.0  6.0  2.0
  ⋅    ⋅   9.0  3.0
  ⋅    ⋅    ⋅   1.0
permutation:
4-element Vector{Int64}:
 4
 2
 3
 1

julia> C.U[1:C.rank, :]' * C.U[1:C.rank, :] ≈ A[C.p, C.p]
true

julia> l, u = C; # destructuring via iteration

julia> l == C.L && u == C.U
true
```


In [31]:
function qr_decomposition(A, b)
    B  = LinearAlgebra.qr(A)
    R = collect(B.R)
    Q = collect(B.Q)
    zeros = [0 0 0]
    R = [R; zeros]
    
    
    y = Q\b
    x = R\y
    
    return x

end

qr_decomposition (generic function with 1 method)

In [32]:
A = [1 3 1; 1 3 7; 1 -1 -4; 1 -1 2]

qr_decomposition(A, b)
# LinearAlgebra.qr(A)
# F = LinearAlgebra.qr(A)
# collect(F.Q)
# collect(F.R)

3-element Vector{Float64}:
 1.0
 0.0
 0.0

In [65]:
function qr_factorization(A, b)
    B  = LinearAlgebra.qr(A)
    R = Matrix(B.R)
    Q = Matrix(B.Q)
    
    y = Q\b
    x = R\y
    return x
end

qr_factorization (generic function with 1 method)

In [66]:
qr_factorization(A,b)

3-element Vector{Float64}:
  1.0
  4.625929269271487e-17
 -3.7007434154171876e-17

In [63]:
function svd_decomposition(A, b)
    a_svd = svd(A)
    
    U = a_svd.U
    Vt = a_svd.Vt
    S = diagm(a_svd.S)
    
    x = (U*S*Vt)\b
    return x

end

svd_decomposition (generic function with 1 method)

In [64]:
svd_decomposition(A,b)

3-element Vector{Float64}:
  0.9999999999999998
 -1.726076226731756e-16
  1.03920512360392e-16

In [56]:
F = svd(A)

u = F.U
vt = F.Vt
s = F.S

3-element Vector{Float64}:
 9.039685945310081
 3.037928933460727
 1.7478746538025831

In [58]:
u

4×3 Matrix{Float64}:
 -0.241309   0.817716   -0.152022
 -0.849048   0.0237597  -0.168977
  0.438432   0.30868    -0.680069
 -0.169306  -0.485276   -0.697024

In [59]:
vt

3×3 Matrix{Float64}:
 -0.0908473  -0.391628  -0.915628
  0.218859    0.8891    -0.401997
 -0.971518    0.236914  -0.00493921

In [60]:
s

3-element Vector{Float64}:
 9.039685945310081
 3.037928933460727
 1.7478746538025831

In [62]:
diagm(s)

3×3 Matrix{Float64}:
 9.03969  0.0      0.0
 0.0      3.03793  0.0
 0.0      0.0      1.74787